/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicsAlgos;

import com.sun.prism.GraphicsPipeline;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Robot;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.image.BufferedImage;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Apar
 */
public class ScanLineBoard extends javax.swing.JFrame implements MouseMotionListener, MouseListener{

    /**
     * Creates new form ScanLineBoard
     */
    private int x_min=50,y_min=50;
    private int x_window=1250,y_window=700;
    private int window=950;
    static Graphics graphics,gg;
    int delay=40;
    
    // specific variables
    private int vertexCount=0;
    ArrayList<Vertex> verticesList=new ArrayList<Vertex>();
    Vertex prevVertex,curVertex;
    private int totalVerticesCount=4;
    private int max_x=1300,max_y=700;
    private int y_pol_max=Integer.MIN_VALUE,x_pol_max=Integer.MIN_VALUE;
    private int y_pol_min=Integer.MAX_VALUE,x_pol_min=Integer.MAX_VALUE;
    private final Color final_color=Color.YELLOW,
                        path_color=Color.ORANGE ;
    private final java.awt.Color initial_color=java.awt.Color.yellow,
                   source_color=java.awt.Color.decode("#EE82EE"),
                   background_color=java.awt.Color.decode("#d6d9e0"),
                   dest_color=Color.green,
                   temp_color=Color.decode("#A2B582"),
                   black_color=Color.BLACK;
//    private int sourceX=0,sourceY=0;
//    private int destX=0,destY=0;
////    private int max_x=window/width,max_y=y_window/width;
//    private int board[][]=new int[max_x][max_x];
//    private int visited[][]=new int[max_x][max_x];
//    private int cost[][]=new int[max_x][max_x];
//    private boolean isFound=false;
//    private boolean srcChange=false,destChange=false;
//    private static int algoIndex=-1;
    private boolean init=true;    
    
    
    // experimental variables
    BufferedImage img;
    
    public ScanLineBoard() {
        initComponents();
        addMouseMotionListener(this);
//        this.addMouseMotionListener(this);
        addMouseListener(this);
        img=new BufferedImage(700, 700, BufferedImage.TYPE_INT_RGB);
        gg=img.getGraphics();
        
    }
    public void draw()
    {
        gg.setColor(Color.WHITE);
        gg.fillRect(0, 0, 700, 700);
        gg.setColor(Color.BLACK);
//        gg.drawOval(100, 100, 20, 20);
//        getGraphics().drawImage(img, 0, 00, this);
    }
    public void paint(Graphics g)
    {
        if(init)
        {
            draw();
            init=false;
        }
        super.paint(g);
        graphics=g;
        g.drawImage(img, 0, 0, this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Scan Line");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(993, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//        System.out.println(""+img.getRGB(500, 500));   
//        Color c=new Color(img.getRGB(100, 100));
//         System.out.println(""+c);
//        int x=1;
//        if(x==1)
//            return;
        
        graphics=getGraphics();
        graphics.setColor(path_color);
        boolean fill=false;
        
        for(int j=y_pol_min+1;j<y_pol_max;j+=2)
        {
            fill=false;
            for(int i=x_pol_min;i<x_pol_max;i+=1)
            {
                Color c=new Color(img.getRGB(i, j));
                if(c.equals(Color.BLACK))
                {
//                    System.err.println(i+"-"+j);
                    fill=!fill;
                    continue;
                }
                if(fill)
                {
                    img.setRGB(i, j, path_color.getRGB());
                    getGraphics().drawImage(img, 0, 00, this);                    
                }
//                graphics.getColor();
//                if(fill)
//                {
//                    
//                }
            }
            
        }
//System.out.println("pixel"+getPixel(10,10));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScanLineBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScanLineBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScanLineBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScanLineBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScanLineBoard().setVisible(true);
            }
        });
    }

    @Override
    public void mouseDragged(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseMoved(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            if(vertexCount<2){
//                
//            }
//            else{
//                graphics=getGraphics();
//                graphics.setColor(Color.BLACK);
//                graphics.drawLine(prevVertex.getX(), prevVertex.getY(), me.getX(), me.getY());
//            }
    }

    @Override
    public void mouseClicked(MouseEvent me) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//        System.out.println("Clicked");
                graphics=getGraphics();
                graphics.setColor(Color.BLACK);
                int x=me.getX(),y=me.getY();
                System.out.println(x+" "+y);
//                x=me.getXOnScreen();
//                y=me.getYOnScreen();
                y_pol_min=Math.min(y, y_pol_min);
                x_pol_min=Math.min(x, x_pol_min);
                y_pol_max=Math.max(y, y_pol_max);
                x_pol_max=Math.max(x, y_pol_max);
                
                System.out.println(x+" "+y);               
                if(x>=max_x || y>=max_y) return;
                Vertex v1=new Vertex(x,y);
                verticesList.add(v1);
                graphics.drawOval(x, y, 1, 1);
                if(vertexCount>0 && vertexCount<totalVerticesCount)
                {
//                    int[] ar={prevVertex.getX(),prevVertex.getX()+10,x,x+2};
//                    int br[]={prevVertex.getY(),prevVertex.getY()+10,y,y+2};
//                   
//                    gg.fillPolygon(ar, br, 4);
                    gg.drawLine(prevVertex.getX(), prevVertex.getY(), x, y);
                    graphics.drawImage(img, 0, 0, null);
                }
                else if(vertexCount>=totalVerticesCount){
                    JOptionPane.showMessageDialog(null, "Maximum Vertices Already Drawn");
                }
                vertexCount++;
                prevVertex=v1;
                if(vertexCount==totalVerticesCount)
                {
//                    int[] ar={prevVertex.getX(),prevVertex.getX()+2,verticesList.get(0).getX(),verticesList.get(0).getX()+2};
//                    int br[]={prevVertex.getY(),prevVertex.getY()+2, verticesList.get(0).getY(), verticesList.get(0).getY()+2};
//                   
//                    gg.fillPolygon(ar, br, 4);
                    gg.drawLine(prevVertex.getX(), prevVertex.getY(),
                            verticesList.get(0).getX(), verticesList.get(0).getY());
                    graphics.drawImage(img, 0, 0, null);
                }
                
            
    }

    @Override
    public void mousePressed(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent me) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
