/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorting;

import searching.*;
import GraphicsAlgos.*;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author Apar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private int x_window=(int) screenSize.getWidth()*90/100;
    private int y_window=(int) screenSize.getHeight()*90/100;
    private int window=x_window*80/100;
    private int panel_height=y_window*70/100;
    
    
    public Main() {
        initComponents();
        setLayout(null);          
        setSize(x_window, y_window);
        panelSorting();
        JPanel panel=new JPanel();  
//        panel.setBounds(x_window*2/100,y_window*15/100,x_window*20/100,panel_height);    
//        panel.setBackground(Color.gray);  
////        JButton b1=new JButton("Button 1");     
//////        b1.setBounds(0,0,0,0);    
////        b1.setBackground(Color.yellow);   
////        JButton b2=new JButton("Button 2");   
//////        b2.setBounds(100,100,80,30);    
////        b2.setBackground(Color.green);   
////        panel.add(b1); panel.add(b2);  
//        add(panel);  
        panelSearching();
//        panel=new JPanel();  
//        panel.setBounds(x_window*27/100,y_window*15/100,x_window*20/100,panel_height);       
//        panel.setBackground(Color.gray);   
//        add(panel);
//        panel=new JPanel();      
//        panel.setBackground(Color.gray);
//        panel.setBounds(x_window*52/100,y_window*15/100,x_window*20/100,panel_height);  
//        add(panel);
//        panel=new JPanel();      
//        panel.setBackground(Color.gray);
//        panel.setBounds(x_window*77/100,y_window*15/100,x_window*20/100,panel_height);  
//        add(panel);
        panelFill();
        panelNode();
        
        // top horizontal panel
        panel=new JPanel();  
        panel.setBounds(0,10,x_window,y_window*10/100);      
        JLabel wlcm_label=new JLabel("Visualiser");
        wlcm_label.setFont(new java.awt.Font("Tahoma", 3, 30));
        wlcm_label.setBounds(0,0,x_window,y_window*10/100); 
        wlcm_label.setForeground(new java.awt.Color(102, 51, 255));
        wlcm_label.setText("Welcome to Algorithms Visualsier");
        wlcm_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(wlcm_label);
        add(panel);
        Graphics g=getGraphics();
        
        
    }
    public void paint(Graphics g)
    {
        super.paint(g);
        g.setColor(Color.BLACK);
        g.drawLine(x_window*25/100, y_window*15/100,  x_window*25/100, y_window*95/100);
        g.drawLine(x_window*50/100, y_window*15/100,  x_window*50/100, y_window*95/100);
        g.drawLine(x_window*75/100, y_window*15/100,  x_window*75/100, y_window*95/100);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setPreferredSize(new java.awt.Dimension(1200, 720));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
void panelFill()
{
    
   JPanel panel=new JPanel();  
        panel.setBounds(x_window*75/100,y_window*15/100,x_window*21/100,panel_height);       
//        panel.setBackground(Color.gray);         
        panel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        JButton button= new JButton("5");
        c.fill = GridBagConstraints.HORIZONTAL;
//c.gridx = 0;
//c.gridy = 0;
//panel.add(button, c);

JLabel j2=new JLabel("Sorting");

JLabel jLabel4=new JLabel("Fill Algorithms");
jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
jLabel4.setForeground(new java.awt.Color(153, 0, 153));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,30,0);
c.gridy = 0;
panel.add(jLabel4, c);


j2=new JLabel();
j2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorting/flood_fill_algorithm.jpg")));
j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
j2.setFont(new java.awt.Font("Tahoma", 0, 25));
        j2.setForeground(Color.decode("#f00000"));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,10,0);
c.gridheight=1;
c.gridy = 1;
panel.add(j2, c);




//jScrollPane2.setViewportView(jTextArea2);
JTextArea jta=new JTextArea("Visually sense the uniform searching \n(Linear Search) and interval seaching\n(Binary Search) algorithms. And see \nhow these algorithms hanlde data in\nreal time.");
jta.setEditable(false);
jta.setColumns(20);
jta.setFont(new java.awt.Font("Rupee Foradian Standard Serif", 0, 18)); // NOI18N
jta.setRows(5);

c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(50,0,10,0);
c.gridy = 2;
panel.add(jta, c);


j2=new JLabel("");
j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
j2.setFont(new java.awt.Font("Tahoma", 0, 25));
        j2.setForeground(Color.decode("#f00000"));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,30,0);
c.gridy = 3;
panel.add(j2, c);

button = new JButton("Explore Now");
button.setBackground(new java.awt.Color(66, 144, 245));
button.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 21)); // NOI18N
button.setForeground(new java.awt.Color(255, 255, 255));
button.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        fill(evt);
    }
   });
c.fill = GridBagConstraints.HORIZONTAL;
c.ipady = 40;       //reset to default
//c.weighty = 1.0;   //request any extra vertical space
c.anchor = GridBagConstraints.PAGE_END; //bottom of space
c.insets = new Insets(30,0,30,0);  //top padding
c.gridx = 0;       //aligned with button 2
c.gridwidth = 3;   //2 columns wide
c.gridy = 4;       //third row
panel.add(button, c);
    add(panel);
}

void panelNode()
{
    
   JPanel panel=new JPanel();  
    panel.setBounds(x_window*52/100,y_window*15/100,x_window*21/100,panel_height);   
//        panel.setBackground(Color.gray);         
        panel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        JButton button= new JButton("5");
        c.fill = GridBagConstraints.HORIZONTAL;
//c.gridx = 0;
//c.gridy = 0;
//panel.add(button, c);

JLabel j2=new JLabel("Sorting");

JLabel jLabel4=new JLabel("Node Searching");
jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
jLabel4.setForeground(new java.awt.Color(153, 0, 153));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,30,0);
c.gridy = 0;
panel.add(jLabel4, c);


j2=new JLabel();
j2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorting/path.jpg")));
j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
j2.setFont(new java.awt.Font("Tahoma", 0, 25));
        j2.setForeground(Color.decode("#f00000"));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,10,0);
c.gridheight=1;
c.gridy = 1;
panel.add(j2, c);




//jScrollPane2.setViewportView(jTextArea2);
JTextArea jta=new JTextArea("Visually sense the uniform searching \n(Linear Search) and interval seaching\n(Binary Search) algorithms. And see \nhow these algorithms hanlde data in\nreal time.");
jta.setEditable(false);
jta.setColumns(20);
jta.setFont(new java.awt.Font("Rupee Foradian Standard Serif", 0, 18)); // NOI18N
jta.setRows(5);

c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(50,0,10,0);
c.gridy = 2;
panel.add(jta, c);


j2=new JLabel("");
j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
j2.setFont(new java.awt.Font("Tahoma", 0, 25));
        j2.setForeground(Color.decode("#f00000"));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,30,0);
c.gridy = 3;
panel.add(j2, c);

button = new JButton("Explore Now");
button.setBackground(new java.awt.Color(66, 144, 245));
button.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 21)); // NOI18N
button.setForeground(new java.awt.Color(255, 255, 255));
button.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        node(evt);
    }
   });
c.fill = GridBagConstraints.HORIZONTAL;
c.ipady = 40;       //reset to default
//c.weighty = 1.0;   //request any extra vertical space
c.anchor = GridBagConstraints.PAGE_END; //bottom of space
c.insets = new Insets(30,0,30,0);  //top padding
c.gridx = 0;       //aligned with button 2
c.gridwidth = 3;   //2 columns wide
c.gridy = 4;       //third row
panel.add(button, c);
    add(panel);
}
void panelSearching()
{
    
   JPanel panel=new JPanel();  
        panel.setBounds(x_window*27/100,y_window*15/100,x_window*21/100,panel_height);       
//        panel.setBackground(Color.gray);         
        panel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        JButton button= new JButton("5");
        c.fill = GridBagConstraints.HORIZONTAL;
//c.gridx = 0;
//c.gridy = 0;
//panel.add(button, c);

JLabel j2=new JLabel("Sorting");

JLabel jLabel4=new JLabel("Element Searching");
jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
jLabel4.setForeground(new java.awt.Color(153, 0, 153));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,30,0);
c.gridy = 0;
panel.add(jLabel4, c);


j2=new JLabel();
j2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorting/images.jpg")));
j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
j2.setFont(new java.awt.Font("Tahoma", 0, 25));
        j2.setForeground(Color.decode("#f00000"));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,10,0);
c.gridheight=1;
c.gridy = 1;
panel.add(j2, c);




//jScrollPane2.setViewportView(jTextArea2);
JTextArea jta=new JTextArea("Visually sense the uniform searching \n(Linear Search) and interval seaching\n(Binary Search) algorithms. And see \nhow these algorithms hanlde data in\nreal time.");
jta.setEditable(false);
jta.setColumns(20);
jta.setFont(new java.awt.Font("Rupee Foradian Standard Serif", 0, 18)); // NOI18N
jta.setRows(5);

c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(50,0,10,0);
c.gridy = 2;
panel.add(jta, c);


j2=new JLabel("");
j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
j2.setFont(new java.awt.Font("Tahoma", 0, 25));
        j2.setForeground(Color.decode("#f00000"));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,30,0);
c.gridy = 3;
panel.add(j2, c);

button = new JButton("Explore Now");
button.setBackground(new java.awt.Color(66, 144, 245));
button.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 21)); // NOI18N
button.setForeground(new java.awt.Color(255, 255, 255));
button.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        search(evt);
    }
   });
c.fill = GridBagConstraints.HORIZONTAL;
c.ipady = 40;       //reset to default
//c.weighty = 1.0;   //request any extra vertical space
c.anchor = GridBagConstraints.PAGE_END; //bottom of space
c.insets = new Insets(30,0,30,0);  //top padding
c.gridx = 0;       //aligned with button 2
c.gridwidth = 3;   //2 columns wide
c.gridy = 4;       //third row
panel.add(button, c);
    add(panel);
}
void panelSorting()
{
    
   JPanel panel=new JPanel();  
        panel.setBounds(x_window*2/100,y_window*15/100,x_window*21/100,panel_height);       
//        panel.setBackground(Color.gray);         
        panel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        JButton button= new JButton("5");
        c.fill = GridBagConstraints.HORIZONTAL;
//c.gridx = 0;
//c.gridy = 0;
//panel.add(button, c);

JLabel j2=new JLabel("Sorting");

JLabel jLabel4=new JLabel("Sorting");
jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
jLabel4.setForeground(new java.awt.Color(153, 0, 153));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,30,0);
c.gridy = 0;
panel.add(jLabel4, c);


j2=new JLabel();
j2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorting/download.png")));
j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
j2.setFont(new java.awt.Font("Tahoma", 0, 25));
        j2.setForeground(Color.decode("#f00000"));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,10,0);
c.gridheight=1;
c.gridy = 1;
panel.add(j2, c);




//jScrollPane2.setViewportView(jTextArea2);
JTextArea jta=new JTextArea("Visually sense the uniform searching \n(Linear Search) and interval seaching\n(Binary Search) algorithms. And see \nhow these algorithms hanlde data in\nreal time.");
jta.setEditable(false);
jta.setColumns(20);
jta.setFont(new java.awt.Font("Rupee Foradian Standard Serif", 0, 18)); // NOI18N
jta.setRows(5);

c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(50,0,10,0);
c.gridy = 2;
panel.add(jta, c);


j2=new JLabel("");
j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
j2.setFont(new java.awt.Font("Tahoma", 0, 25));
        j2.setForeground(Color.decode("#f00000"));
c.fill = GridBagConstraints.HORIZONTAL;
c.weightx = 0.5;
c.gridx = 1;
c.insets = new Insets(30,0,30,0);
c.gridy = 3;
panel.add(j2, c);

button = new JButton("Explore Now");
button.setBackground(new java.awt.Color(66, 144, 245));
button.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 21)); // NOI18N
button.setForeground(new java.awt.Color(255, 255, 255));
button.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        sort(evt);
    }
   });

c.fill = GridBagConstraints.HORIZONTAL;
c.ipady = 40;       //reset to default
//c.weighty = 1.0;   //request any extra vertical space
c.anchor = GridBagConstraints.PAGE_END; //bottom of space
c.insets = new Insets(30,0,30,0);  //top padding
c.gridx = 0;       //aligned with button 2
c.gridwidth = 3;   //2 columns wide
c.gridy = 4;       //third row
panel.add(button, c);
    add(panel);
}
private void sort(ActionEvent evt) {
//           throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Controller cntr=new Controller();
        cntr.setVisible(true);
        this.dispose();
            
    }
private void search(ActionEvent evt) {
//           throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        SearchingController cntr=new SearchingController();
        cntr.setVisible(true);
        this.dispose();
            
    }
private void node(ActionEvent evt) {
//           throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        TestForm tf=new TestForm();
        this.dispose();
        tf.setVisible(true);
            
    }
private void fill(ActionEvent evt) {
//           throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        FillColor tf=new FillColor();
        this.dispose();
        tf.setVisible(true);
            
    }
}
